### ISSUE TITLE
Total results count is incorrect after filtering

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#142]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Total results count is incorrect after filtering](https://trello.com/c/LyKQHmki/363-total-results-count-is-incorrect-after-filtering)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Total results count is incorrect after filtering](https://trello.com/c/LyKQHmki/363-total-results-count-is-incorrect-after-filtering)
