### ISSUE TITLE
Breadcrumb arrows are missing

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#143]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Breadcrumb arrows are missing](https://trello.com/c/sTXsWvnd/362-breadcrumb-arrows-are-missing)

**Comment by maxf** [comment]
Oddly, the server returns a 500 when queried for the icon:
https://beta.data.gov.uk/assets/separator-2x.png
