### ISSUE TITLE
No datasets seem to show location data

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#144]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [None of the datasets seem to displaying a geographic location field (all showing ‘Not available’) - is this a bug or bad data?](https://trello.com/c/nnZpMC3G/376-none-of-the-datasets-seem-to-displaying-a-geographic-location-field-all-showing-not-available-is-this-a-bug-or-bad-data)
