### ISSUE TITLE
Most recent filter does not work, last updated is set incorrectly

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#145]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Most recent filter not working - all datasets have last updated set to the same date - Aug 2017](https://trello.com/c/9u6o89zd/375-most-recent-filter-not-working-all-datasets-have-last-updated-set-to-the-same-date-aug-2017)
