### ISSUE TITLE
Related datasets do not take query filters into account

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#146]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Related datasets have do not take query filters into account](https://trello.com/c/m9Ga3rvM/374-related-datasets-have-do-not-take-query-filters-into-account)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Related datasets have do not take query filters into account](https://trello.com/c/m9Ga3rvM/374-related-datasets-have-do-not-take-query-filters-into-account)
