### ISSUE TITLE
View instead of Download link for HTML datafile links

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#147]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [“Download” label for html-type data files doesn’t make sense. Change to “View” if link is to html](https://trello.com/c/Kzj3bLIl/364-download-label-for-html-type-data-files-doesnt-make-sense-change-to-view-if-link-is-to-html)
