### ISSUE TITLE
Top vertical alignment of columns on dataset page layout needs to be fixed

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#148]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top vertical alignment of columns on dataset page layout needs to be fixed](https://trello.com/c/rhGWpn5X/365-top-vertical-alignment-of-columns-on-dataset-page-layout-needs-to-be-fixed)
