### ISSUE TITLE
Fix HTML escapes in dataset descriptions

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#149]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix things like &amp; on dataset descriptions](https://trello.com/c/tKJwN2Vi/360-fix-things-like-amp-on-dataset-descriptions)
