### ISSUE TITLE
Full integration - show published datasets in elasticsearch on Find

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#15]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Point find-data at Elastic on AWS](https://trello.com/c/d20NePXr/234-point-find-data-at-elastic-on-aws)

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re-index Publish-Beta datasets onto Elastic](https://trello.com/c/Jx4G20VV/232-re-index-publish-beta-datasets-onto-elastic)

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Load legacy data onto PaaS database](https://trello.com/c/twcygkzT/233-load-legacy-data-onto-paas-database)

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configure find to use the shared elastic instance](https://trello.com/c/1945doxe/271-configure-find-to-use-the-shared-elastic-instance)

**Comment by hannako** [comment]
This ticket has been split out - old and irrelevant!
