### ISSUE TITLE
Last updated column header wraps over two lines

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#150]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Last updated column needs to be wider so the heading doesn't wrap over two lines](https://trello.com/c/tB0z4l3O/367-last-updated-column-needs-to-be-wider-so-the-heading-doesnt-wrap-over-two-lines)
