### ISSUE TITLE
Last updated column does not have an obvious empty state

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#151]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Last updated" column doesn’t have an empty state so it looks broken](https://trello.com/c/kDeSNrCA/373-last-updated-column-doesnt-have-an-empty-state-so-it-looks-broken)
