### ISSUE TITLE
“Remove filters” link needs to be placed under “apply filters”

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#152]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [“Remove filters” link needs to be placed under “apply filters”](https://trello.com/c/fqCPDVM2/361-remove-filters-link-needs-to-be-placed-under-apply-filters)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [“Remove filters” link needs to be placed under “apply filters”](https://trello.com/c/fqCPDVM2/361-remove-filters-link-needs-to-be-placed-under-apply-filters)
