### ISSUE TITLE
Vertical spacing on home between heading, paragraph and search box needs to be fixed

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#153]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Vertical spacing on home between heading, paragraph and search box needs to be fixed](https://trello.com/c/OO126Xrl/366-vertical-spacing-on-home-between-heading-paragraph-and-search-box-needs-to-be-fixed)
