### ISSUE TITLE
Filter parlance not appearing at top of search results

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#156]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gauntlet Bug Fixes](https://trello.com/c/i3BEJXyD/353-gauntlet-bug-fixes)

**Comment by maxf** [comment]
@govuklaurence I'm not sure what the problem is. Currently it does show things like "0 results found for ‘cat’ published by ‘Department for Regional Development’ filtered by ‘Greater London’"

**Comment by nicholsj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filters are not being displayed up in the summary of search results and filters applied](https://trello.com/c/PXfDVVLp/368-filters-are-not-being-displayed-up-in-the-summary-of-search-results-and-filters-applied)
