### ISSUE TITLE
JS testing

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#159]
Related to #158, which will identify where changes will be most impactful.

**Comment by hannako** [comment]
1. Install simple cov
2.  List of user stories from Louise. Build feature test for each user stories
3. Edge case testing once 2. is complete

**Comment by hannako** [comment]
1 is done
2: https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/13bZdtQKUtyDDwanx_RQdqwAZZPVXSDrzkx104z9tYAQ/edit?usp=sharing_eil&ts=59b10826

**Comment by hannako** [comment]
Test required for location and publisher filter
Tests required for show-hide and groupings
