### ISSUE TITLE
Search results sorting back end

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/find_data_beta#23]

**Comment by hannako** [comment]
Remove sort by options on left of screen and replace with drop down filter as per Blanca's designs 
https://projects.invisionapp.com/d/main#/console/11687113/246684233/preview

**Comment by hannako** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search Results: implement changes to sorting results](https://trello.com/c/n03yLFS6/330-search-results-implement-changes-to-sorting-results)
