### ISSUE TITLE
Configure Publish to point at this Beta

### ISSUE THREAD

**Issue by rossjones** [datagovuk/find_data_beta#8]

**Comment by govuklaurence** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re-index Publish-Beta datasets onto Elastic](https://trello.com/c/Jx4G20VV/232-re-index-publish-beta-datasets-onto-elastic)

**Comment by rossjones** [comment]
We can't do this for PaaS until Publish is on PaaS.  Have imported some of the data into heroku, but used too many resources and it kicked me out.  Will keep open until done for PaaS.
